# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0bd05739674eb4fe955f1157a458f29836f4493db75f501573d307d6b65cb554d558db62769af7f2b88d6b58f3cf2c886fb69f122e4dddba7145be43c40a167e

test:
  secret_key_base: e9ba908df7cc0253d6b6372ce463b3997c6f26ea6a1ed26c51776779c025d648a122550988b86aa1d7d8b902807e0b5dcbe6d325e887d42538523db1eca59661

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
